Program Dz_15;
Uses Crt;
Var str,typeAnimal:string;
  ch:char;
begin
while(true) do
  begin
  Write('Введіть букву: ');
  Readln(str);
  ch:= str[1];
  ch:=LowerCase(ch);
  case ch of 
    'а':begin
          Writeln('Акула');
          typeAnimal:='Хижак';
        end;
    'б':begin
          Writeln('Баран');
          typeAnimal:='Свійский';
        end;
    'в':begin
          Writeln('Ведмідь');
          typeAnimal:='Хижак';
        end;
    'г':begin
          Writeln('Гусак');
          typeAnimal:='Птах';
        end;
     'ґ':begin
          Writeln('ґ');
          typeAnimal:='Птах';
        end;
      'д':begin
          Writeln('Динозавр');
          typeAnimal:='Хижак';
        end;
     'е':begin
          Writeln('Енелята');
          typeAnimal:='Свійський';
        end;
      'є':begin
          Writeln('Єнот');
          typeAnimal:='Хижак';
        end;
      'ж':begin
          Writeln('Жаба');
          typeAnimal:='Свійський';
        end;
     'з':begin
          Writeln('Зебра');
          typeAnimal:='Свійський';
        end;
      'и':begin
          Writeln('Индик');
          typeAnimal:='Птах';
        end;
      'і':begin
          Writeln('Ігуванна');
          typeAnimal:='Хижак';
        end;
       'ї':begin
          Writeln('Їжак');
          typeAnimal:='Свійський';
        end;
    'й':begin
          Writeln('Йорк');
          typeAnimal:='Хижак';
        end;
    'к':begin
          Writeln('Кит');
          typeAnimal:='Хижак';
        end;
    'л':begin
          Writeln('Лис');
          typeAnimal:='Хижак';
        end;
     'м':begin
          Writeln('Мураха');
          typeAnimal:='Свійський';
        end;
      'н':begin
          Writeln('Носоріг');
          typeAnimal:='Свійський';
        end;
     'о':begin
          Writeln('Оса');
          typeAnimal:='Свійський';
        end;
      'п':begin
          Writeln('Пінгвін');
          typeAnimal:='Птах';
        end;
      'р':begin
          Writeln('Равлик');
          typeAnimal:='Свійський';
        end;
     'с':begin
          Writeln('Слон');
          typeAnimal:='Свійський';
        end;
      'т':begin
          Writeln('Тукан');
          typeAnimal:='Птах';
        end;
      'у':begin
          Writeln('Удав');
          typeAnimal:='Хижак';
        end;
      'ф':begin
          Writeln('Фламінго');
          typeAnimal:='Свійський';
        end;
       'х':begin
          Writeln('Хомяк');
          typeAnimal:='Свійський';
        end;
        'ц':begin
          Writeln('Цап');
          typeAnimal:='Свійський';
        end;
        'ч':begin
          Writeln('Черепаха');
          typeAnimal:='Свійський';
        end;
        'ш':begin
          Writeln('Шпак');
          typeAnimal:='Птах';
        end;
        'щ':begin
          Writeln('Щука');
          typeAnimal:='Хижак';
        end;
        'ь':begin
          Writeln('ььььь');
          typeAnimal:='Хижак';
        end;
        'ю':begin
          Writeln('ююююю');
          typeAnimal:='Хижак';
        end;
        'я':begin
          Writeln('Як');
          typeAnimal:='Свійський';
        end;
      else
        begin
          Writeln('Ошибка');
        end;
  end;
  Writeln(typeAnimal);
  end;
end.